name: jupyterlab-deck-docs

channels:
  - conda-forge
  - nodefaults

dependencies:
  - python >=3.10,<3.11
  ### environment-base.yml ###
  - doit-with-toml
  - ipywidgets >=8.0.4
  - jupyterlab >=3.5.2,<4
  - jupyterlab_widgets >=3.0.5
  - jupyterlab-fonts >=2.1.1
  - pip
  - python >=3.7,<3.11
  ### environment-base.yml ###
  ### environment-build.yml ###
  # runtimes
  - nodejs >=16,!=17.*,<19
  # host app
  - ipywidgets >=8.0.4
  # build
  - flit >=3.7.1
  - twine
  ### environment-build.yml ###
  ### environment-docs.yml ###
  # demo
  - ipydrawio
  - jupyter-videochat
  - jupyterlab-myst <1.10
  # - jupyterlab-webrtc-docprovider
  # docs
  - docutils >=0.18
  - pydata-sphinx-theme
  - sphinx >=5.1,<6
  - sphinx-autobuild
  - sphinx-copybutton
  - myst-nb
  # check
  - hunspell
  - hunspell-en
  - pytest-check-links
  # lite cruft
  - pkginfo
  - python-libarchive-c
  - pip:
      - jupyterlite ==0.1.0b18
  ### environment-docs.yml ###
